#!/bin/bash
docker run  -it \
            -w /opt \
            -v "$(pwd)"/:/opt/ \
            -v ~/.ssh:/root/.ssh \
            -v "$(pwd)"/.terraformrc:/root/.terraformrc \
            hashicorp/terraform:1.3.5 $@

