version: '3'
services:
  nocodb_app: 
    container_name: nocodb_app
    environment: 
      NC_DB: "${CONN_STRING}"
      NC_MIGRATIONS_DISABLED: true 
    image: "nocodb/nocodb:0.99.0"
    ports:
      - 80:8080
    restart: always