#!/bin/bash
export TF_VAR_token="$(yc iam create-token)" 
export TF_VAR_cloud_id="$(yc config get cloud-id)" 
export TF_VAR_folder_id="$(yc config get folder-id)" 
export TF_VAR_local_public_ip="$(curl -s ifconfig.co)" 
export TF_VAR_local_subnet="$(ip -j route get 8.8.8.8 | jq -r '.[0].prefsrc')/32" 
export TF_VAR_project_dir="$(pwd)"
terraform $@